### ISSUE TITLE
Link to user item does not work from user profile

### ISSUE THREAD

**Issue by rmaree** [shareish/shareish#22]
When going to a user profile then clicking on one of their item, the link https://shareish.org/items/XXX?kind=user  is not displaying the item page. But when clicking from the Browse Items page, the link https://shareish.org/items/XXX is working 

BAD REQUEST Axios
Request failed with status code 404

**Comment by banneux-florent** [comment]
Solved in the new version from branch [/settings-notifications](https://github.com/shareish/shareish/tree/feature/settings-notifications)? No longer 404 error for me. Item page render correctly on [https://shareish.org/items/XXX?kind=user](https://shareish.org/items/XXX?kind=user).

**Comment by banneux-florent** [comment]
URL parameter ?kind=user removed from frontend, was useless there, on branch [fix/various](https://github.com/shareish/shareish/compare/main...fix/various), commit [06993ed](https://github.com/shareish/shareish/commit/06993edaa54783592937fd91e95e30128115d2f5).
