### ISSUE TITLE
fix: logged in on the same account on two different places makes first one unusable

### ISSUE THREAD

**Issue by banneux-florent** [shareish/shareish#31]
When logged in on a first browser and logging-in on a second one on the same account, it overwrites the auth token of the first one in the database, which makes it (the first one) unusable (can't even logout, requires cookies/session deletion).

**Comment by banneux-florent** [comment]
@rmaree could this be closed? Using Shareish on several supports with the same account now works, only issue is that when you logout from any of those supports, it disconnects all the other ones.

**Comment by rmaree** [comment]
solved by commit 59b623a
