### ISSUE TITLE
feat: autocomplete choice for item name using ai model on multiple images

### ISSUE THREAD

**Issue by rmaree** [shareish/shareish#39]
1) using only one image: change the behavior of the autocompletion of the item name when uploading an image: let the user choose among the top 5 categories using an autocomplete form https://buefy.org/documentation/autocomplete

2) using multiple uploaded image: aggregate the predictions for each image

**Comment by banneux-florent** [comment]
Added in commit [88599de](https://github.com/shareish/shareish/commit/88599de4ab313ecdb6296f7e10bf0fa36ba96e40) on branch [feat/multiple-images](https://github.com/shareish/shareish/compare/main...feature/multiple-images).
