### ISSUE TITLE
fix: conversations messages date handling inconsistency 

### ISSUE THREAD

**Issue by banneux-florent** [shareish/shareish#80]
In the backend, at the `Message` model definition, we can find `date = models.DateTimeField(auto_now_add=True)` which, when a new row is inserted, automatically sets the value of the date field to the current date regardless of the given value.

But, in the frontend, in the `src/views/TheConversationsView.vue` in the `sendMessage()` function, through WebSocket we send a parameter `'date': new Date()` which is received, at the end of the process, in backend in the `save_message()` function from file `mymap/consumers.py` where we can see the `date` parameter used and passed to the `Message.objects.create()` function, but where its affected value will never be used.

That makes the parameter useless in the frontend.

Two solutions:

1. Keep the parameter in the frontend, and switch the `date` field of the `Message` model from `models.DateTimeField(auto_now_add=True)` to `models.DateTimeField(default=timezone.now)`. With this default value, it will only fill the field upon create()/insertion if the later is empty. Upside is that it can offer a more precise time of sending, if the user encounters some poor internet connection or so. Major downside is that it'll require a more secure way of transmitting the date as it opens a "breach" where the user can bypass the normal VueJS implementation of the WebSocket and can transmit any date he wants (in the future or in the past if not handled).

2. Remove the frontend implementation of the date parameter making the backend the only one handling it by keeping the current model structure (date will correspond to whenever the backend receives the message, just as it is working right now).

Any thought? I would go for the second one. Easy fix and prevent headaches!

A lot of explanations but for some reason I randomly thought about that issue and went to test the possible vulnerability, didn't want to leave one open if I could fix it quickly!

I'm open to do this fix on a new branch whenever I'll get an answer here.

**Comment by rmaree** [comment]
Hello Florent,
Thanks for the notice ! I would also go for 2). Would be great if you could implement it within a specific branch !

**Comment by banneux-florent** [comment]
> Hello Florent, Thanks for the notice ! I would also go for 2). But what is the impact for users having different timezones, everything will be aligned based on backend timezone ? Would be great if you could implement it within a specific branch !

If I'm not wrong, datetimes in postgre store timezones too ("+00:00" in database), so all the messages will be sync on this "+00:00" timezone. Once displayed in the frontend, it should automatically transform and use the client timezone. I'll try that out.
