### ISSUE TITLE
fix: reference address not refreshed on Reference address & Notifications page

### ISSUE THREAD

**Issue by rmaree** [shareish/shareish#94]
On the account notifications settings page, type and save a new reference address, then go to Account tab, then go back to Reference address & Notifications tab: the old address is still there, only a hard refresh shows the new address.

**Comment by banneux-florent** [comment]
Solved!

The issue was for the all the settings pages by the way (profile, account and notifications). An error in `TheSettingsView.vue`. Looping through the user object the wrong way when updating the values.
